server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-727231.okta.com/oauth2/default
    client-id: 0oa276p844RkFkXWA357
    client-secret: 6bk6aYJVgLIPmRTeATNg8QbpJmqKSk2NUPVf2fMp
spring:
  thymeleaf:
    cache: false